config/routes.rb
Csportal::Application.routes.draw do
resources :logins
resources :projects
resources :sessions, only: [:new, :create, :destroy]

  get "on_call/new"

  get "on_call/edit"

  match '/release',     to: 'home#release'
  match '/active',      to: 'home#active'
  match '/oncall',      to: 'home#oncall'
  match '/whose',       to: 'home#whose'
  match '/root',         to: 'home#index'

  match '/add',         to: 'oncall#new'
  match '/modify',      to: 'oncal#edit'

  match '/signup',      to: 'logins#new'
  match '/signin',      to: 'sessions#new'
  match '/signout',     to: 'sessions#destroy', via: :delete

  match '/entry',       to: 'projects#new'
  match '/list',        to: 'projects#show'

  

   root :to => 'home#index'

end

app/models/login.rb
class Login < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |login| login.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: { with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false } 

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

private
    
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :am, :client, :conf, :jira, :name, :pm, :qa, :team

 	# before_save { |project| project.am = am.downcase 
  #   project.pm = pm.downcase,
  #   project.qa = qa.downcase,
  #   project.team = team.downcase,
  #   project.client = client.downcase,
  #   project.name = name.downcase }

    validates :client, presence: true,
  				uniqueness: { case_sensitive: false }
    validates :name, presence: true
    validates :team, presence: true
    validates :am, presence: true
    validates :pm, presence: true
    validates :qa, presence: true
    


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	include SessionsHelper

	def handle_unverified_request
	    sign_out
	    super
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def release
  end

  def active
  end

  def whose
  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
	def show
		@login = Login.find(params[:id])
	end

	def new
		@login = Login.new
	end

	def create
		@login = Login.new(params[:login])
		if @login.save
			flash[:success] = "User created successfuly!"
			redirect_to @login
			# Handle a successful save.
		else
			render 'new'
		end
	end
  
end

app/controllers/on_call_controller.rb
class OnCallController < ApplicationController
  def new
  end

  def edit
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController

	def show
  		@project = Project.all
  	end
  
	def new
		@project = Project.new
	end

	def create
	    @project = Project.new(params[:project])
    	if @project.save
    		redirect_to @project
      	# Handle a successful save.
		else
    		render 'new'
    	end
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def show
  		@project = Project.find(params[:id])
  	end
  
	def new
		@project = Project.new
	end

	def create
	    @project = Project.new(params[:project])
    	if @project.save
    		flash[:success] = "Entry created successfuly!"
    		redirect_to @project
      	# Handle a successful save.
		else
    		render 'new'
    	end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		login = Login.find_by_email(params[:session][:email].downcase)
  		if login && login.authenticate(params[:session][:password])
  			sign_in login
      		redirect_to root_path
		else
			flash.now[:error] = 'Invalid email/password combination'
      		render 'new'
		end
	end

	def destroy
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

 # Takes input from page and tests content, adds if not blank, per page.
  def full_title(page_title)
    base_title = "CS Portal"
    if page_title.empty?
		base_title
	else
      "#{base_title} | #{page_title}"
    end
end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/on_call_helper.rb
module OnCallHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(login)
    	cookies.permanent[:remember_token] = login.remember_token
    	self.current_user = login
	end

	def signed_in?
	    !current_user.nil?
	end

	def current_user=(login)
    	@current_user = login
	end

	def current_user
	    @current_user ||= Login.find_by_remember_token(cookies[:remember_token])
	end



end

app/views/home/active.html.erb
<% provide(:title, 'Active Development') %>
<!DOCTYPE html>
  	<h1>Idea: Interactive Calendar of Projects in Active Development</h1>

app/views/home/index.html.erb
<!DOCTYPE html>
<div class="box flex row">
  <div id="left" class="column">
    <div id="feed_holder">
        <a class="twitter-timeline" href="https://twitter.com/Moovweb" data-widget-id="344307862346006529">Tweets by @Moovweb</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
  </div>
  <div id="right" class="column">
    Development & Project Management
    <div id="dev" class="box flex">
        <div class="people">
          <div class="name">Very Long Name</div>
          <div class="name">2nd</div>
          <div class="name">3rd</div>
          <div class="name">4th</div>
          <div class="name">Phil</div>
        </div>
        <div class="tele">
          <div class="number">###-###-####</div>
          <div class="number">###-###-####</div>
          <div class="number">###-###-####</div>
          <div class="number">###-###-####</div>
          <div class="number">###-###-####</div>
        </div>
        <div class="mail box flex column">
          <div id="1st">
            <%= link_to "1st@moovweb.com", 'mailto:emailm@moovweb.com', class: "email" %>
          </div>
          <div id="2nd">
          <%= link_to "2nd@moovweb.com", 'mailto:emailm@moovweb.com', class: "email" %>
          </div>
          <div id="3rd">
          <%= link_to "3rd@moovweb.com", 'mailto:emailm@moovweb.com', class: "email" %>
          </div>
          <div id="4th">
          <%= link_to "4th@moovweb.com", 'mailto:emailm@moovweb.com', class: "email" %>
          </div>
          <div id="5th">
          <%= link_to "5th@moovweb.com", 'mailto:emailm@moovweb.com', class: "email" %>
          </div>
        </div>
    </div>
    Operations
    <div id="ops" class="box flex row">
      <div class="people column">
        <div class="name">Operations</div>
        <div class="name">Platform</div>
      </div>
      <div class="tele column">
        <div class="number">###-###-####</div>
        <div class="number">###-###-####</div>
      </div>
      <div class ="mail column">
        <div id="opsM">
          <%= link_to "ops@moovweb.com", 'mailto:emailm@moovweb.com', class: "email" %>
        </div>
        <div>
          <%= link_to "platform@moovweb.com", 'mailto:emailm@moovweb.com', class: "email" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/oncall.html.erb
<% provide(:title, 'On-Call Schedule') %>
<!DOCTYPE html>
  	<h1>Idea: Up Coming On-Call Schedule, up to 4 weeks out.</h1>

app/views/home/release.html.erb
<% provide(:title, 'LSM Releases') %>
<!DOCTYPE html>
	<h1>Idea: Interactive Calendar of Upcoming Releases Site releases for LSM Projects</h1>

app/views/home/whose.html.erb
<% provide(:title, 'Whose Project Is It?') %>
<div class ="left column">
	<%= link_to "Create a New Project", entry_path, class: "navLink btn" %>
	<%= link_to "Find Information About Current Projects", "#", class: "navLink btn" %>
</div>
<div class = "right">
	<h1>Idea: Searchable database of Project info, any criteria search able</h1>
</div>

app/views/layouts/_footer.html.erb
<footer class="foot">
	<div>Copyright 2013.</div>
	<div>Issues/Concerns? <%= link_to "E-mail me and let me know.", 'mailto:james.gill@moovweb.com?Subject=Portal' %></div>
</footer>

app/views/layouts/_header.html.erb
<header class="head">
	<div id="m_logo">
    <%= link_to  image_tag("logo.png"), 'http://www.moovweb.com', class: "logo" %>
	</div>
	<div id="h_logo",>
		<%= link_to image_tag("alt-title.png"), '/', class: "logo" %>
	</div>
	<div id="mainNav" class="box flex row" >
		<div id="navList">
	    <%= link_to "LSM Release Schedule", release_path, class: "navLink" %>
	    <%= link_to "Active Dev Projects", active_path, class: "navLink" %>
	    <%= link_to "On-Call Schedule", oncall_path, class: "navLink" %>
	    <%= link_to "Whose Project Is It?", whose_path, class: "navLink" %>
	    <%= link_to "Apollo", 'https://console.moovweb.com/', class: "navLink", target: "_blank" %>
	    <%= link_to "Confluence", 'https://moovwebconfluence.atlassian.net', class: "navLink", target: "_blank" %>
	    <%= link_to "Jira", 'https://moovwebconfluence.atlassian.net', class: "navLink", target: "_blank" %>
	    <% if signed_in? %>
			<li id="fat-menu" class="dropdown navLink">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
            <ul class="dropdown-menu">
				<li><%= link_to "Profile", current_user %></li> <li><%= link_to "Settings", '#' %></li>
				<li class="divider"></li>
				<li>
				<%= link_to "Sign out", signout_path, method: "delete" %> </li>
				</ul>
		<% else %>
		<% end %>
	    </div>
 	</div>
 	
</header>

app/views/layouts/_signin.html.erb
<% provide(:title, "Sign in") %>
<h1>Sign in</h1>


<div>
	<div>
		<%= form_for(:session, url: sessions_path) do |f| %>

		<%= f.label :email %>
		<%= f.text_field :email %> <%= f.label :password %>
		<%= f.password_field :password %>

		<div>
			<%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
		</div>
		<% end %>

		<p>New user? <%= link_to "Sign up now!", signup_path %></p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/header' %>
<body>
	
	<div class="mainWrapper box flex">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<% if signed_in? %>
			<%= yield %>
		<% else %>
			<%= render "layouts/signin" %>
		<% end %>
	</div>
</body>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>

app/views/logins/index.html.erb
<% provide(:title, @logins.name) %>
	

app/views/logins/new.html.erb
<% provide(:title, 'New Login') %>
<div><h1>Create new Login</h1></div>


<div id="formholder column">
	<%= form_for(@login) do |f| %>
		<%= render 'shared/error_messages_login' %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
			
		<div>
			<%= f.submit "Create new Login", class:"btn btn-large btn-primary" %>
		</div>
		
	<% end %>
</div>

app/views/logins/show.html.erb
<% provide(:title, @login.name) %>
<h1>Displaying db record <%= @login.id %></h1>
<h2><%= @login.name %>, <%= @login.email %></h2>

app/views/logins/signup.html.erb
<% provide(:title, 'signup') %>
<h1>Login Creation</h1>

<div id="formholder">
	<%= form_for(@logins) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.text_field :password %>

		<%= f.label :password_confirmation %>
		<%= f.text_field :password_confirmation %>

		<%= f.submit "Create new Login", id:"subtmit" %>
	<% end %>
</div>

app/views/logins/whose.html.erb
<% provide(:title, 'Whose Project Is It?') %>
<h2>Idea: Searchable database for Project Info, by whatever criteria</h2>

app/views/on_call/edit.html.erb
<h1>OnCall#edit</h1>
<p>Find me in app/views/on_call/edit.html.erb</p>

app/views/on_call/new.html.erb
<h1>OnCall#new</h1>
<p>Find me in app/views/on_call/new.html.erb</p>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h1>Create new Project Listing</h1>

<div class ="row">
	<div class="span6 offset3">
		<%= form_for(@project) do |f| %>
			<%= render 'shared/error_messages_project' %>

			<%= f.label :client, "Client Name" %>
			<%= f.text_field :client %>

			<%= f.label :name, "Project Name" %>
			<%= f.text_field :name %>

			<%= f.label :team, "Development Team" %>
			<%= f.text_field :team %>

			<%= f.label :am, "Account Manager" %>
			<%= f.text_field :am %>

			<%= f.label :pm, "Project Manager" %>
			<%= f.text_field :pm %>

			<%= f.label :qa, "QA Engineer" %>
			<%= f.text_field :qa %>

			<%= f.label :conf, "Confluence"%>
			<%= f.text_field :conf %>		

			<%= f.label :jira, "Jira" %>
			<%= f.text_field :jira %>		

			<div>
			<%= f.submit "Create new Project", class:"btn btn-large btn-primary" %>
			</div>
		<% end %>
	</div>
</div>

app/views/projects/show.html.erb
<% provide(:title, 'Project Information') %>

<% provide(:title, @project.name) %>

<div class="column">
	<h1>Displaying db record <%= @project.id %></h1>
</div>
<div class="column">
	<h2>Client: <%= @project.client %></h2>
	<h2>Project Name: <%= @project.name %></h2>
	<h2>Development Team: <%= @project.team %></h2>
	<h2>Account Manager: <%= @project.am %></h2>
	<h2>Project Manager: <%= @project.pm %></h2>
	<h2>QA Engineer: <%= @project.qa %></h2>
	<h2>Confluence Page: <%= @project.conf %></h2>
	<h2>Jira Page: <%= @project.jira %></h2>
</div>

app/views/shared/_error_messages.html.erb
<% if @project.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@project.errors.count, "error") %>.
		</div>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li> <% end %>
		</ul>
	</div>
 <% end %>

app/views/shared/_error_messages_login.html.erb
<% if @login.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@login.errors.count, "error") %>.
		</div>
		<ul>
			<% @login.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li> <% end %>
		</ul>
	</div>
 <% end %>

app/views/shared/_error_messages_project.html.erb
<% if @project.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@project.errors.count, "error") %>.
		</div>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li> <% end %>
		</ul>
	</div>
 <% end %>